const CACHE='flap-tap-v1';
const ASSETS=["./", "./index.html", "./manifest.json", "./assets/background_day.png", "./assets/background_night.png", "./assets/background_sunrise.png", "./assets/background_sunset.png", "./assets/bird_sheet_day.png", "./assets/bird_sheet_night.png", "./assets/bird_sheet_sunrise.png", "./assets/bird_sheet_sunset.png", "./assets/cloud_sheet_day.png", "./assets/cloud_sheet_night.png", "./assets/cloud_sheet_sunrise.png", "./assets/cloud_sheet_sunset.png", "./assets/crashed_text.png", "./assets/feather_sheet_day.png", "./assets/feather_sheet_night.png", "./assets/feather_sheet_sunrise.png", "./assets/feather_sheet_sunset.png", "./assets/ground_day.png", "./assets/ground_night.png", "./assets/ground_sunrise.png", "./assets/ground_sunset.png", "./assets/icon-192.png", "./assets/icon-512.png", "./assets/pillar_base_day.png", "./assets/pillar_base_night.png", "./assets/pillar_base_sunrise.png", "./assets/pillar_base_sunset.png", "./assets/pillar_broken_bottom_sheet_day.png", "./assets/pillar_broken_bottom_sheet_night.png", "./assets/pillar_broken_bottom_sheet_sunrise.png", "./assets/pillar_broken_bottom_sheet_sunset.png", "./assets/pillar_broken_top_sheet_day.png", "./assets/pillar_broken_top_sheet_night.png", "./assets/pillar_broken_top_sheet_sunrise.png", "./assets/pillar_broken_top_sheet_sunset.png", "./assets/pillar_column_day.png", "./assets/pillar_column_night.png", "./assets/pillar_column_sunrise.png", "./assets/pillar_column_sunset.png", "./assets/rotate_phone.png", "./assets/shooting_star.png", "./assets/sky_day.png", "./assets/sky_night.png", "./assets/sky_sunrise.png", "./assets/sky_sunset.png", "./assets/star_1.png", "./assets/star_2.png", "./assets/star_sheet.png", "./assets/title_logo.png", "./assets/ui_leaderboard.png", "./assets/ui_panel.png", "./assets/ui_settings.png"];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', e => { e.waitUntil(self.clients.claim()); });
self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  e.respondWith(caches.match(e.request).then(r => r || fetch(e.request).catch(() => caches.match('./index.html'))));
});
